"""Compatibility facade for the split :mod:`rlff.rewards` implementation."""

# ruff: noqa: F401 -- this module intentionally preserves the former module namespace.

from __future__ import annotations

from .aggregation import (
    _ensure_sequence,
    _invalid_reward_message,
    aggregate_role_rewards,
    create_reward_provider,
    score_completions,
    score_rollout_group,
    score_trajectories,
)
from .payloads import (
    _character,
    _full_trajectory_history,
    _history_text,
    _indexed_utters,
    _merged_tasks,
    _proxy_characters,
    _proxy_episode_value,
    _proxy_field,
    _trajectory_character_completions,
    _turn_payload,
    build_completion_reward_payload,
    build_proxy_completion_reward_payload,
    build_proxy_trajectory_reward_payload,
    build_trajectory_reward_payload,
)
from .prompts import (
    _parse_model_response,
    _reward_response_debug,
    _validate_prompt_text,
    load_reward_prompt,
    load_reward_prompts,
    parse_completion_reward_response,
    parse_reward_response,
    parse_trajectory_reward_response,
    render_reward_prompt,
)
from .protocol import (
    _ACTION_DIMENSION_INDEX,
    _ACTION_MARKUP_PATTERN,
    _NO_ACTION_SCORE,
    _PROMPT_VARIABLE_PATTERN,
    CHAT_COMPLETIONS_PATH,
    COMPLETION_DIMENSIONS,
    COMPLETION_REWARD_PROMPT_FILENAME,
    DEEPSEEK_V4_FLASH_PROVIDER,
    DEFAULT_REPAIR_PROMPT,
    PLACEHOLDER_MARKER,
    PLACEHOLDER_PROVIDER,
    QWEN3_7_FLASH_PROVIDER,
    QWEN_DASHSCOPE_GENERATION_URL,
    QWEN_DASHSCOPE_PROVIDER,
    REPAIR_REWARD_PROMPT_FILENAME,
    REWARD_PROMPT_VERSION,
    REWARD_REQUEST_SCHEMA_VERSION,
    REWARD_RESPONSE_SCHEMA_VERSION,
    TRAJECTORY_REWARD_PROMPT_FILENAME,
    CompletionRewardResponse,
    CompletionScore,
    RewardAggregationError,
    RewardError,
    RewardPromptError,
    RewardPrompts,
    RewardResponseError,
    RewardTransportError,
    TrajectoryRewardResponse,
    TrajectoryTaskScore,
    _score_value,
    _StrictModel,
)
from .provider_base import PlaceholderRewardProvider, _placeholder_audit, _RewardProviderBase
from .providers import DeepSeekRewardProvider, QwenDashScopeRewardProvider
from .response_scoring import (
    completion_effective_values,
    completion_response_reward,
    completion_response_rewards,
    trajectory_response_reward,
)
from .transport import (
    LangSmithTracer,
    _call_transport,
    _default_reward_transport,
    _json_payload,
    _redact,
    _response_from_transport,
)
from .transport_types import (
    RewardBatch,
    RewardHTTPResponse,
    RewardProvider,
    RewardTransport,
    RewardTransportCallable,
    RewardTransportResult,
)

__all__ = [
    "CHAT_COMPLETIONS_PATH",
    "COMPLETION_DIMENSIONS",
    "COMPLETION_REWARD_PROMPT_FILENAME",
    "DEEPSEEK_V4_FLASH_PROVIDER",
    "PLACEHOLDER_MARKER",
    "PLACEHOLDER_PROVIDER",
    "QWEN3_7_FLASH_PROVIDER",
    "QWEN_DASHSCOPE_GENERATION_URL",
    "QWEN_DASHSCOPE_PROVIDER",
    "REWARD_PROMPT_VERSION",
    "REWARD_REQUEST_SCHEMA_VERSION",
    "REWARD_RESPONSE_SCHEMA_VERSION",
    "TRAJECTORY_REWARD_PROMPT_FILENAME",
    "CompletionRewardResponse",
    "CompletionScore",
    "DeepSeekRewardProvider",
    "LangSmithTracer",
    "PlaceholderRewardProvider",
    "QwenDashScopeRewardProvider",
    "RewardAggregationError",
    "RewardBatch",
    "RewardError",
    "RewardHTTPResponse",
    "RewardPromptError",
    "RewardPrompts",
    "RewardProvider",
    "RewardResponseError",
    "RewardTransport",
    "RewardTransportError",
    "TrajectoryRewardResponse",
    "TrajectoryTaskScore",
    "aggregate_role_rewards",
    "build_completion_reward_payload",
    "build_proxy_completion_reward_payload",
    "build_proxy_trajectory_reward_payload",
    "build_trajectory_reward_payload",
    "completion_effective_values",
    "create_reward_provider",
    "load_reward_prompt",
    "load_reward_prompts",
    "parse_completion_reward_response",
    "parse_reward_response",
    "parse_trajectory_reward_response",
    "render_reward_prompt",
    "score_completions",
    "score_rollout_group",
    "score_trajectories",
]
